* Import library

*   * LEVEL 1

In [2]:
import pandas as pd

* Soal 1.1

In [3]:
Suhu = {'Senin': 24, 'Selasa': 26, 'Rabu': 23, 'Kamis': 25, 'Jumat': 27}

In [4]:
Suhu_index = pd.Series(Suhu, index = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], name = 'Suhu')

In [5]:
Suhu_index

Senin     24
Selasa    26
Rabu      23
Kamis     25
Jumat     27
Name: Suhu, dtype: int64

* Soal 1.2

In [6]:
Suhu = pd.Series([23, 26, 23, 25, 27], index = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'], name = 'Suhu')

In [7]:
Suhu.mean()

np.float64(24.8)

In [8]:
Suhu.min()

23

In [9]:
Suhu.max()

27

In [10]:
Suhu.idxmax()

'Jumat'

* Soal 1.3

In [11]:
buah = {'nama_buah': ['apel', 'jeruk', 'mangga', 'pisang'], 'harga': [30000, 20000, 25000, 15000], 'stok': [12, 20, 8, 25]}
Buah = pd.DataFrame(buah).set_index('nama_buah')

In [12]:
Buah

           harga  stok
nama_buah
apel       30000    12
jeruk      20000    20
mangga     25000     8
pisang     15000    25

* Soal 1.4

In [13]:
Buah['harga']

nama_buah
apel      30000
jeruk     20000
mangga    25000
pisang    15000
Name: harga, dtype: int64

In [14]:
Buah.shape

(4, 2)

* Soal 1.5

In [15]:
nilai_stok = Buah['harga'] * Buah['stok']
print(nilai_stok)

nama_buah
apel      360000
jeruk     400000
mangga    200000
pisang    375000
dtype: int64

*   * LEVEL 2

In [16]:
data_siswa = {
    "nama": ["Andi", "Bunga", "Citra", "Dimas", "Eka", "Fajar", "Gita",
             "Hana", "Irfan", "Joko", "Kiki", "Lina", "Eka"],
    "jenis_kelamin": ["L", "P", "P", "L", "P", "L", "P",
                      "P", "L", "L", "P", "P", "P"],
    "kelas": ["X RPL 1", "X RPL 1", "X RPL 2", "X RPL 2", "X RPL 1", "X RPL 2", "X RPL 2",
              "X RPL 1", "X RPL 1", "X RPL 2", "X RPL 1", "X RPL 2", "X RPL 1"],
    "matematika": [78, 88, 92, 65, 70, 85, 75, 95, 60, 82, 90, 68, 70],
    "informatika": [85, 90, None, 72, 80, 95, 70, 88, 75, 78, 92, 65, 80],
    "bahasa_inggris": [70, 85, 88, 60, 75, 78, None, 92, 65, 80, 87, 72, 75],
    "kehadiran": [95, 98, 100, 85, 90, 97, 92, 100, 80, 94, 96, 88, 90],
    "ekskul": ["Robotik", "Paduan Suara", "Robotik", "Futsal", "Pramuka", "Robotik", "Paduan Suara",
               "Pramuka", "Futsal", "Futsal", "Robotik", "Pramuka", "Pramuka"],
}

df = pd.DataFrame(data_siswa)

* Soal 2.1

In [17]:
df.head()

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul
0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik
1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara
2,Citra,P,X RPL 2,92,NaN,88.0,100,Robotik
3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal
4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka

* Soal 2.2

In [18]:
df.tail(3)

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul
10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik
11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka
12,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka

* Soal 2.3

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nama            13 non-null     object
 1   jenis_kelamin   13 non-null     object
 2   kelas           13 non-null     object
 3   matematika      13 non-null     int64
 4   informatika     12 non-null     float64
 5   bahasa_inggris  12 non-null     float64
 6   kehadiran       13 non-null     int64
 7   ekskul          13 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 964.0+ bytes

Data yang kosong ada di column 'informatika' dan 'bahasa_inggris' karena memiliki 12 non-null sedangkan yang lainnya memiliki 13 non-null

Tipe data pada kolom 'matematika' berbeda dengan 'informatika' karena pada kolom matematika tidak memiliki data kosong atau (None) sedangkan pada kolom 'informatika' memiliki data (None) otomatis membuat tipe data berubah ke float

* Soal 2.4

In [20]:
df.describe()

       matematika  informatika  bahasa_inggris   kehadiran
count   13.000000    12.000000       12.000000   13.000000
mean    78.307692    80.833333       77.250000   92.692308
std     11.264876     9.379216        9.696532    5.977522
min     60.000000    65.000000       60.000000   80.000000
25%     70.000000    74.250000       71.500000   90.000000
50%     78.000000    80.000000       76.500000   94.000000
75%     88.000000    88.500000       85.500000   97.000000
max     95.000000    95.000000       92.000000  100.000000

Nilai Rata-rata (Mean) dari data matematika adalah '78.307692' (78 Jika di bulatkan)

Nilai Tertinggi (Max) yang ada di informatika adalah 95 dan nilai Terendah (Min) nya adalah 65

Baris count berbeda dengan matematika karena di data informatika memiliki data (None) sedangkan data matematika tidak memiliki data (None) yang membuat data informatika tidak sama dengan data matematika

* Soal 2.5

In [21]:
df.duplicated(keep=False).sum()

np.int64(2)

Ada 2 data yang Teridentifikasi duplikat

*   * LEVEL 3

* Soal 3.1

In [22]:
df[['nama', 'matematika']]

     nama  matematika
0    Andi          78
1   Bunga          88
2   Citra          92
3   Dimas          65
4     Eka          70
5   Fajar          85
6    Gita          75
7    Hana          95
8   Irfan          60
9    Joko          82
10   Kiki          90
11   Lina          68
12    Eka          70

* Soal 3.2

In [23]:
df.iloc[2:6]

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul
2,Citra,P,X RPL 2,92,NaN,88.0,100,Robotik
3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal
4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka
5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik

* Soal 3.3

In [24]:
df.loc[df.matematika > 80, ['nama', 'matematika']]

     nama  matematika
1   Bunga          88
2   Citra          92
5   Fajar          85
7    Hana          95
9    Joko          82
10   Kiki          90

Ada 6 siswa yang nilai matematikanya di atas 80

* Soal 3.4

In [25]:
df.loc[(df.jenis_kelamin == 'P') & (df.kelas == 'X RPL 2'), ['nama', 'matematika', 'informatika']]

     nama  matematika  informatika
2   Citra          92          NaN
6    Gita          75         70.0
11   Lina          68         65.0

Ada 3 siswa Perempuan di kelas X RPL 2

* Soal 3.5

In [26]:
df.loc[df.ekskul.isin(['Robotik', 'Futsal']), ['nama', 'ekskul']]

     nama   ekskul
0    Andi  Robotik
2   Citra  Robotik
3   Dimas   Futsal
5   Fajar  Robotik
8   Irfan   Futsal
9    Joko   Futsal
10   Kiki  Robotik

Ada 7 siswa yang mengikuti eksul Futsal dan Robotik

* Soal 3.6

In [27]:
df.loc[df.kehadiran >= 90, ['nama', 'kehadiran']]

     nama  kehadiran
0    Andi         95
1   Bunga         98
2   Citra        100
4     Eka         90
5   Fajar         97
6    Gita         92
7    Hana        100
9    Joko         94
10   Kiki         96
12    Eka         90

*   * LEVEL 4

* Soal 4.1

In [28]:
df.isna().sum()

nama              0
jenis_kelamin     0
kelas             0
matematika        0
informatika       1
bahasa_inggris    1
kehadiran         0
ekskul            0
dtype: int64

ada 2 data kosong

* Soal 4.2

In [29]:
df.duplicated().sum()
df_bersih = df.drop_duplicates()

In [30]:
df_bersih

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul
0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik
1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara
2,Citra,P,X RPL 2,92,NaN,88.0,100,Robotik
3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal
4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka
5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik
6,Gita,P,X RPL 2,75,70.0,NaN,92,Paduan Suara
7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka
8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal
9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal
10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik
11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka

Awalnya ada 13 data lalu data yang teridentifikasi duplikat di hapus dan menjadi 12 data

* Soal 4.3

In [31]:
df_bersih.dropna(inplace=True)

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/2181993857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bersih.dropna(inplace=True)

In [32]:
df_bersih.isna().sum()

nama              0
jenis_kelamin     0
kelas             0
matematika        0
informatika       0
bahasa_inggris    0
kehadiran         0
ekskul            0
dtype: int64

In [33]:
df_bersih

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul
0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik
1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara
3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal
4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka
5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik
7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka
8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal
9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal
10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik
11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka

Hasil setelah menghapus data duplikat dan data kosong, data yang tersisa sekarang ada 10

Sudah tidak ada data kosong

* Soal 4.4

In [34]:
# .Round(1) untuk mengambil 1 angka di belakang koma
rata_rata = df_bersih[['matematika', 'informatika', 'bahasa_inggris']].mean().round(1)
print(rata_rata)

matematika        78.1
informatika       82.0
bahasa_inggris    76.4
dtype: float64

* Soal 4.5

In [35]:
df_bersih['Rata_rata'] = df_bersih[['matematika', 'informatika', 'bahasa_inggris']].mean(axis=1).round(1)
print(df_bersih['Rata_rata'])

0     77.7
1     87.7
3     65.7
4     75.0
5     86.0
7     91.7
8     66.7
9     80.0
10    89.7
11    68.3
Name: Rata_rata, dtype: float64

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/1388514319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bersih['Rata_rata'] = df_bersih[['matematika', 'informatika', 'bahasa_inggris']].mean(axis=1).round(1)

In [36]:
def cek_status(Rata_rata):
    if Rata_rata >= 75:
        return'Tuntas'
    else:
        return'Remidial'

df_bersih['Status'] = df_bersih['Rata_rata'].apply(cek_status)

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/1192834501.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bersih['Status'] = df_bersih['Rata_rata'].apply(cek_status)

In [37]:
df_bersih

,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul,Rata_rata,Status
0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik,77.7,Tuntas
1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara,87.7,Tuntas
3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal,65.7,Remidial
4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka,75.0,Tuntas
5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik,86.0,Tuntas
7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka,91.7,Tuntas
8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal,66.7,Remidial
9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal,80.0,Tuntas
10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik,89.7,Tuntas
11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka,68.3,Remidial

* Soal 4.6

In [38]:
df_bersih = df_bersih.reset_index()
df_bersih.sort_values(by='Rata_rata', ascending=False)

,index,nama,jenis_kelamin,kelas,matematika,informatika,bahasa_inggris,kehadiran,ekskul,Rata_rata,Status
5,7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka,91.7,Tuntas
8,10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik,89.7,Tuntas
1,1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara,87.7,Tuntas
4,5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik,86.0,Tuntas
7,9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal,80.0,Tuntas
0,0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik,77.7,Tuntas
3,4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka,75.0,Tuntas
9,11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka,68.3,Remidial
6,8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal,66.7,Remidial
2,3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal,65.7,Remidial

* Soal 4.7

In [39]:
df_bersih.rename(columns={'bahasa_inggris': 'b_ing'}, inplace=True)
df_bersih

,index,nama,jenis_kelamin,kelas,matematika,informatika,b_ing,kehadiran,ekskul,Rata_rata,Status
0,0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik,77.7,Tuntas
1,1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara,87.7,Tuntas
2,3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal,65.7,Remidial
3,4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka,75.0,Tuntas
4,5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik,86.0,Tuntas
5,7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka,91.7,Tuntas
6,8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal,66.7,Remidial
7,9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal,80.0,Tuntas
8,10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik,89.7,Tuntas
9,11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka,68.3,Remidial

* Soal 4.8

Mengisi nilai bahasa inggris Gita dari rata" semua siswa tidak adil, guru sebaiknya memberikan tugas tambahan untuk mengisi nilai kosong tersebut

*   * LEVEL 5

* Soal 5.1

In [40]:
df_bersih['kelas'].value_counts()

kelas
X RPL 1    6
X RPL 2    4
Name: count, dtype: int64

* Soal 5.2

In [41]:
df_bersih['ekskul'].value_counts()

ekskul
Robotik         3
Futsal          3
Pramuka         3
Paduan Suara    1
Name: count, dtype: int64

Peminatnya hampir sama semua kecuali yang paduan suara yang hanya memiliki 1 peminat

* Soal 5.3

In [42]:
df_bersih.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          10 non-null     int64
 1   nama           10 non-null     object
 2   jenis_kelamin  10 non-null     object
 3   kelas          10 non-null     object
 4   matematika     10 non-null     int64
 5   informatika    10 non-null     float64
 6   b_ing          10 non-null     float64
 7   kehadiran      10 non-null     int64
 8   ekskul         10 non-null     object
 9   Rata_rata      10 non-null     float64
 10  Status         10 non-null     object
dtypes: float64(3), int64(3), object(5)
memory usage: 1012.0+ bytes

In [43]:
df_bersih.groupby(['kelas', 'matematika', 'informatika', 'b_ing']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/4133517629.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_bersih.groupby(['kelas', 'matematika', 'informatika', 'b_ing']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

                                        index   nama jenis_kelamin    kelas  \
kelas   matematika informatika b_ing
X RPL 1 60         75.0        65.0  6      8  Irfan             L  X RPL 1
                                     6      8  Irfan             L  X RPL 1
                                     6      8  Irfan             L  X RPL 1
                                     6      8  Irfan             L  X RPL 1
                                     6      8  Irfan             L  X RPL 1
...                                       ...    ...           ...      ...
X RPL 2 85         95.0        78.0  4      5  Fajar             L  X RPL 2
                                     4      5  Fajar             L  X RPL 2
                                     4      5  Fajar             L  X RPL 2
                                     4      5  Fajar             L  X RPL 2
                                     4      5  Fajar             L  X RPL 2

                                        matematika  informatika  b_ing  \
kelas   matematika informatika b_ing
X RPL 1 60         75.0        65.0  6          60         75.0   65.0
                                     6          60         75.0   65.0
                                     6          60         75.0   65.0
                                     6          60         75.0   65.0
                                     6          60         75.0   65.0
...                                            ...          ...    ...
X RPL 2 85         95.0        78.0  4          85         95.0   78.0
                                     4          85         95.0   78.0
                                     4          85         95.0   78.0
                                     4          85         95.0   78.0
                                     4          85         95.0   78.0

                                        kehadiran   ekskul  Rata_rata  \
kelas   matematika informatika b_ing
X RPL 1 60         75.0        65.0  6         80   Futsal       66.7
                                     6         80   Futsal       66.7
                                     6         80   Futsal       66.7
                                     6         80   Futsal       66.7
                                     6         80   Futsal       66.7
...                                           ...      ...        ...
X RPL 2 85         95.0        78.0  4         97  Robotik       86.0
                                     4         97  Robotik       86.0
                                     4         97  Robotik       86.0
                                     4         97  Robotik       86.0
                                     4         97  Robotik       86.0

                                          Status
kelas   matematika informatika b_ing
X RPL 1 60         75.0        65.0  6  Remidial
                                     6  Remidial
                                     6  Remidial
                                     6  Remidial
                                     6  Remidial
...                                          ...
X RPL 2 85         95.0        78.0  4    Tuntas
                                     4    Tuntas
                                     4    Tuntas
                                     4    Tuntas
                                     4    Tuntas

[110 rows x 11 columns]

Kelas yang unggul di pelajaran informatika adalah X RPL 2 yang mendapatkan nilai 95

* Soal 5.4

In [44]:
df_bersih.groupby(['jenis_kelamin', 'kehadiran']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/581102619.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_bersih.groupby(['jenis_kelamin', 'kehadiran']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

                           index   nama jenis_kelamin    kelas  matematika  \
jenis_kelamin kehadiran
L             80        6      8  Irfan             L  X RPL 1          60
                        6      8  Irfan             L  X RPL 1          60
                        6      8  Irfan             L  X RPL 1          60
                        6      8  Irfan             L  X RPL 1          60
                        6      8  Irfan             L  X RPL 1          60
...                          ...    ...           ...      ...         ...
P             100       5      7   Hana             P  X RPL 1          95
                        5      7   Hana             P  X RPL 1          95
                        5      7   Hana             P  X RPL 1          95
                        5      7   Hana             P  X RPL 1          95
                        5      7   Hana             P  X RPL 1          95

                           informatika  b_ing  kehadiran   ekskul  Rata_rata  \
jenis_kelamin kehadiran
L             80        6         75.0   65.0         80   Futsal       66.7
                        6         75.0   65.0         80   Futsal       66.7
                        6         75.0   65.0         80   Futsal       66.7
                        6         75.0   65.0         80   Futsal       66.7
                        6         75.0   65.0         80   Futsal       66.7
...                                ...    ...        ...      ...        ...
P             100       5         88.0   92.0        100  Pramuka       91.7
                        5         88.0   92.0        100  Pramuka       91.7
                        5         88.0   92.0        100  Pramuka       91.7
                        5         88.0   92.0        100  Pramuka       91.7
                        5         88.0   92.0        100  Pramuka       91.7

                             Status
jenis_kelamin kehadiran
L             80        6  Remidial
                        6  Remidial
                        6  Remidial
                        6  Remidial
                        6  Remidial
...                             ...
P             100       5    Tuntas
                        5    Tuntas
                        5    Tuntas
                        5    Tuntas
                        5    Tuntas

[110 rows x 11 columns]

* Soal 5.5

In [45]:
df_bersih.groupby('Status').apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/1742327321.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_bersih.groupby('Status').apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

            index   nama jenis_kelamin    kelas  matematika  informatika  \
Status
Remidial 9     11   Lina             P  X RPL 2          68         65.0
         9     11   Lina             P  X RPL 2          68         65.0
         9     11   Lina             P  X RPL 2          68         65.0
         2      3  Dimas             L  X RPL 2          65         72.0
         9     11   Lina             P  X RPL 2          68         65.0
         6      8  Irfan             L  X RPL 1          60         75.0
         9     11   Lina             P  X RPL 2          68         65.0
         9     11   Lina             P  X RPL 2          68         65.0
         9     11   Lina             P  X RPL 2          68         65.0
         9     11   Lina             P  X RPL 2          68         65.0
         2      3  Dimas             L  X RPL 2          65         72.0
Tuntas   8     10   Kiki             P  X RPL 1          90         92.0
         8     10   Kiki             P  X RPL 1          90         92.0
         1      1  Bunga             P  X RPL 1          88         90.0
         4      5  Fajar             L  X RPL 2          85         95.0
         5      7   Hana             P  X RPL 1          95         88.0
         4      5  Fajar             L  X RPL 2          85         95.0
         5      7   Hana             P  X RPL 1          95         88.0
         5      7   Hana             P  X RPL 1          95         88.0
         0      0   Andi             L  X RPL 1          78         85.0
         5      7   Hana             P  X RPL 1          95         88.0
         0      0   Andi             L  X RPL 1          78         85.0

            b_ing  kehadiran        ekskul  Rata_rata    Status
Status
Remidial 9   72.0         88       Pramuka       68.3  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         2   60.0         85        Futsal       65.7  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         6   65.0         80        Futsal       66.7  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         9   72.0         88       Pramuka       68.3  Remidial
         2   60.0         85        Futsal       65.7  Remidial
Tuntas   8   87.0         96       Robotik       89.7    Tuntas
         8   87.0         96       Robotik       89.7    Tuntas
         1   85.0         98  Paduan Suara       87.7    Tuntas
         4   78.0         97       Robotik       86.0    Tuntas
         5   92.0        100       Pramuka       91.7    Tuntas
         4   78.0         97       Robotik       86.0    Tuntas
         5   92.0        100       Pramuka       91.7    Tuntas
         5   92.0        100       Pramuka       91.7    Tuntas
         0   70.0         95       Robotik       77.7    Tuntas
         5   92.0        100       Pramuka       91.7    Tuntas
         0   70.0         95       Robotik       77.7    Tuntas

Kelas yang perlu mendapatkan perhatian lebih adalah X RPL 2

* Soal 5.6

In [46]:
df_bersih.groupby(['Rata_rata']).agg([len, min, max]).sort_values(by='Rata_rata', ascending=False)

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/1113131507.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df_bersih.groupby(['Rata_rata']).agg([len, min, max]).sort_values(by='Rata_rata', ascending=False)
/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/1113131507.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_bersih.groupby(['Rata_rata']).agg([len, min, max]).sort_values(by='Rata_rata', ascending=False)

          index         nama               jenis_kelamin         kelas  ...  \
            len min max  len    min    max           len min max   len  ...
Rata_rata                                                               ...
91.7          1   7   7    1   Hana   Hana             1   P   P     1  ...
89.7          1  10  10    1   Kiki   Kiki             1   P   P     1  ...
87.7          1   1   1    1  Bunga  Bunga             1   P   P     1  ...
86.0          1   5   5    1  Fajar  Fajar             1   L   L     1  ...
80.0          1   9   9    1   Joko   Joko             1   L   L     1  ...
77.7          1   0   0    1   Andi   Andi             1   L   L     1  ...
75.0          1   4   4    1    Eka    Eka             1   P   P     1  ...
68.3          1  11  11    1   Lina   Lina             1   P   P     1  ...
66.7          1   8   8    1  Irfan  Irfan             1   L   L     1  ...
65.7          1   3   3    1  Dimas  Dimas             1   L   L     1  ...

          b_ing kehadiran           ekskul                             Status  \
            max       len  min  max    len           min           max    len
Rata_rata
91.7       92.0         1  100  100      1       Pramuka       Pramuka      1
89.7       87.0         1   96   96      1       Robotik       Robotik      1
87.7       85.0         1   98   98      1  Paduan Suara  Paduan Suara      1
86.0       78.0         1   97   97      1       Robotik       Robotik      1
80.0       80.0         1   94   94      1        Futsal        Futsal      1
77.7       70.0         1   95   95      1       Robotik       Robotik      1
75.0       75.0         1   90   90      1       Pramuka       Pramuka      1
68.3       72.0         1   88   88      1       Pramuka       Pramuka      1
66.7       65.0         1   80   80      1        Futsal        Futsal      1
65.7       60.0         1   85   85      1        Futsal        Futsal      1


                min       max
Rata_rata
91.7         Tuntas    Tuntas
89.7         Tuntas    Tuntas
87.7         Tuntas    Tuntas
86.0         Tuntas    Tuntas
80.0         Tuntas    Tuntas
77.7         Tuntas    Tuntas
75.0         Tuntas    Tuntas
68.3       Remidial  Remidial
66.7       Remidial  Remidial
65.7       Remidial  Remidial

[10 rows x 30 columns]

* Soal 5.7

In [47]:
df_bersih.columns

Index(['index', 'nama', 'jenis_kelamin', 'kelas', 'matematika', 'informatika',
       'b_ing', 'kehadiran', 'ekskul', 'Rata_rata', 'Status'],
      dtype='object')

In [48]:
df_bersih

,index,nama,jenis_kelamin,kelas,matematika,informatika,b_ing,kehadiran,ekskul,Rata_rata,Status
0,0,Andi,L,X RPL 1,78,85.0,70.0,95,Robotik,77.7,Tuntas
1,1,Bunga,P,X RPL 1,88,90.0,85.0,98,Paduan Suara,87.7,Tuntas
2,3,Dimas,L,X RPL 2,65,72.0,60.0,85,Futsal,65.7,Remidial
3,4,Eka,P,X RPL 1,70,80.0,75.0,90,Pramuka,75.0,Tuntas
4,5,Fajar,L,X RPL 2,85,95.0,78.0,97,Robotik,86.0,Tuntas
5,7,Hana,P,X RPL 1,95,88.0,92.0,100,Pramuka,91.7,Tuntas
6,8,Irfan,L,X RPL 1,60,75.0,65.0,80,Futsal,66.7,Remidial
7,9,Joko,L,X RPL 2,82,78.0,80.0,94,Futsal,80.0,Tuntas
8,10,Kiki,P,X RPL 1,90,92.0,87.0,96,Robotik,89.7,Tuntas
9,11,Lina,P,X RPL 2,68,65.0,72.0,88,Pramuka,68.3,Remidial

In [49]:
df_bersih.groupby(['Rata_rata', 'ekskul']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

/var/folders/8v/_f429jcx7lv2yx9w891n346h0000gn/T/ipykernel_3761/2477696426.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_bersih.groupby(['Rata_rata', 'ekskul']).apply(lambda df_bersih: df_bersih.loc[df_bersih.idxmax()])

                     index   nama jenis_kelamin    kelas  matematika  \
Rata_rata ekskul
65.7      Futsal  2      3  Dimas             L  X RPL 2          65
                  2      3  Dimas             L  X RPL 2          65
                  2      3  Dimas             L  X RPL 2          65
                  2      3  Dimas             L  X RPL 2          65
                  2      3  Dimas             L  X RPL 2          65
...                    ...    ...           ...      ...         ...
91.7      Pramuka 5      7   Hana             P  X RPL 1          95
                  5      7   Hana             P  X RPL 1          95
                  5      7   Hana             P  X RPL 1          95
                  5      7   Hana             P  X RPL 1          95
                  5      7   Hana             P  X RPL 1          95

                     informatika  b_ing  kehadiran   ekskul  Rata_rata  \
Rata_rata ekskul
65.7      Futsal  2         72.0   60.0         85   Futsal       65.7
                  2         72.0   60.0         85   Futsal       65.7
                  2         72.0   60.0         85   Futsal       65.7
                  2         72.0   60.0         85   Futsal       65.7
                  2         72.0   60.0         85   Futsal       65.7
...                          ...    ...        ...      ...        ...
91.7      Pramuka 5         88.0   92.0        100  Pramuka       91.7
                  5         88.0   92.0        100  Pramuka       91.7
                  5         88.0   92.0        100  Pramuka       91.7
                  5         88.0   92.0        100  Pramuka       91.7
                  5         88.0   92.0        100  Pramuka       91.7

                       Status
Rata_rata ekskul
65.7      Futsal  2  Remidial
                  2  Remidial
                  2  Remidial
                  2  Remidial
                  2  Remidial
...                       ...
91.7      Pramuka 5    Tuntas
                  5    Tuntas
                  5    Tuntas
                  5    Tuntas
                  5    Tuntas

[110 rows x 11 columns]

Kesimpulan itu tidak dapat dibuktikan di data ini karena rata" anak yang mendapatkan nilai rata" yang tinggi itu mengikuti ekskul pramuka