# Studi Kasus 2 - Lowongan Kerja bidang IT

In [1]:
import pandas as pd 
import io

data_loker = """posisi,perusahaan,kota,pendidikan_min,pengalaman_min,gaji_min_juta,gaji_maks_juta,skill,tipe_kerja
Junior Web Developer,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO
Frontend Developer,CV Rumah Digital,malang,SMK,1,4.0,5.5,JavaScript;React;HTML;CSS,Hybrid
Backend Developer,PT Arunika Solusi,Surabaya ,D3,2,6.0,8.0,Python;Django;SQL;Git,Hybrid
Data Analyst,PT Data Cerdas,JAKARTA,S1,1,7.0,10.0,Python;SQL;Excel,WFO
IT Support,PT Sinar Logistik,Malang,SMK,0,3.0,3.8,Jaringan;Windows;Linux,WFO
Mobile Developer,PT Aplikasi Kita,Surabaya,SMK,1,5.0,7.0,Flutter;Dart;Git,Hybrid
Game Developer,Studio Batu Kreatif,Batu,SMK,0,3.5,5.0,Unity;C#;Git,WFO
QA Tester,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,Testing;SQL;Git,WFO
Data Engineer,PT Data Cerdas,Jakarta,S1,3,12.0,18.0,Python;SQL;Cloud,Remote
Fullstack Developer,PT Teknologi Bromo,Malang,D3,2,,,JavaScript;Node.js;React;SQL,Hybrid
UI/UX Designer,CV Rumah Digital,Malang,SMK,1,4.0,5.0,Figma;HTML;CSS,Hybrid
Junior Programmer,PT Sinar Logistik,Surabaya,SMK,0,4.0,5.0,Python;SQL,WFO
Web Developer,PT Nusa Web,Jakarta,S1,2,8.0,12.0,JavaScript;React;Node.js;Git,Remote
IT Support,PT Bank Daerah,surabaya,D3,1,4.5,6.0,Jaringan;Windows,WFO
Data Analyst,PT Arunika Solusi,Surabaya,S1,0,5.5,7.5,Python;SQL;Excel;Power BI,Hybrid
Mobile Developer,PT Nusa Web,Jakarta,D3,2,9.0,13.0,Kotlin;Android;Git,Remote
Junior Web Developer,PT Teknologi Bromo,Malang,SMK,0,,,HTML;CSS;JavaScript;PHP,WFO
Game Developer,PT Main Seru,Jakarta,D3,1,7.0,9.0,Unity;C#,Hybrid
Backend Developer,PT Kode Nusantara,Malang,SMK,1,4.5,6.0,PHP;Laravel;MySQL;Git,Hybrid
Junior Web Developer,PT Kode Nusantara,Malang ,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO
"""

loker = pd.read_csv(io.StringIO(data_loker))

In [2]:
loker

,posisi,perusahaan,kota,pendidikan_min,pengalaman_min,gaji_min_juta,gaji_maks_juta,skill,tipe_kerja
0,Junior Web Developer,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO
1,Frontend Developer,CV Rumah Digital,malang,SMK,1,4.0,5.5,JavaScript;React;HTML;CSS,Hybrid
2,Backend Developer,PT Arunika Solusi,Surabaya,D3,2,6.0,8.0,Python;Django;SQL;Git,Hybrid
3,Data Analyst,PT Data Cerdas,JAKARTA,S1,1,7.0,10.0,Python;SQL;Excel,WFO
4,IT Support,PT Sinar Logistik,Malang,SMK,0,3.0,3.8,Jaringan;Windows;Linux,WFO
5,Mobile Developer,PT Aplikasi Kita,Surabaya,SMK,1,5.0,7.0,Flutter;Dart;Git,Hybrid
6,Game Developer,Studio Batu Kreatif,Batu,SMK,0,3.5,5.0,Unity;C#;Git,WFO
7,QA Tester,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,Testing;SQL;Git,WFO
8,Data Engineer,PT Data Cerdas,Jakarta,S1,3,12.0,18.0,Python;SQL;Cloud,Remote
9,Fullstack Developer,PT Teknologi Bromo,Malang,D3,2,NaN,NaN,JavaScript;Node.js;React;SQL,Hybrid
10,UI/UX Designer,CV Rumah Digital,Malang,SMK,1,4.0,5.0,Figma;HTML;CSS,Hybrid
11,Junior Programmer,PT Sinar Logistik,Surabaya,SMK,0,4.0,5.0,Python;SQL,WFO
12,Web Developer,PT Nusa Web,Jakarta,S1,2,8.0,12.0,JavaScript;React;Node.js;Git,Remote
13,IT Support,PT Bank Daerah,surabaya,D3,1,4.5,6.0,Jaringan;Windows,WFO
14,Data Analyst,PT Arunika Solusi,Surabaya,S1,0,5.5,7.5,Python;SQL;Excel;Power BI,Hybrid
15,Mobile Developer,PT Nusa Web,Jakarta,D3,2,9.0,13.0,Kotlin;Android;Git,Remote
16,Junior Web Developer,PT Teknologi Bromo,Malang,SMK,0,NaN,NaN,HTML;CSS;JavaScript;PHP,WFO
17,Game Developer,PT Main Seru,Jakarta,D3,1,7.0,9.0,Unity;C#,Hybrid
18,Backend Developer,PT Kode Nusantara,Malang,SMK,1,4.5,6.0,PHP;Laravel;MySQL;Git,Hybrid
19,Junior Web Developer,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO

* Tahap 1

In [3]:
loker.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   posisi          20 non-null     object
 1   perusahaan      20 non-null     object
 2   kota            20 non-null     object
 3   pendidikan_min  20 non-null     object
 4   pengalaman_min  20 non-null     int64
 5   gaji_min_juta   18 non-null     float64
 6   gaji_maks_juta  18 non-null     float64
 7   skill           20 non-null     object
 8   tipe_kerja      20 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 1.5+ KB

In [4]:
loker.isna().sum()

posisi            0
perusahaan        0
kota              0
pendidikan_min    0
pengalaman_min    0
gaji_min_juta     2
gaji_maks_juta    2
skill             0
tipe_kerja        0
dtype: int64

In [5]:
loker['kota'].unique()

array(['Malang', 'malang', 'Surabaya ', 'JAKARTA', 'Surabaya', 'Batu',
       'Jakarta', 'surabaya', 'Malang '], dtype=object)

Masalahyang ditemukan ada Case-Sensitive dan ada data yang kosong di 2 column gaji_min_juta dan gaji_max_juta

* Tahap 2

In [6]:
loker['kota']

0        Malang
1        malang
2     Surabaya
3       JAKARTA
4        Malang
5      Surabaya
6          Batu
7        Malang
8       Jakarta
9        Malang
10       Malang
11     Surabaya
12      Jakarta
13     surabaya
14     Surabaya
15      Jakarta
16       Malang
17      Jakarta
18       Malang
19      Malang
Name: kota, dtype: object

In [7]:
loker['kota'] = loker['kota'].str.strip().str.title()

In [8]:
loker['kota']

0       Malang
1       Malang
2     Surabaya
3      Jakarta
4       Malang
5     Surabaya
6         Batu
7       Malang
8      Jakarta
9       Malang
10      Malang
11    Surabaya
12     Jakarta
13    Surabaya
14    Surabaya
15     Jakarta
16      Malang
17     Jakarta
18      Malang
19      Malang
Name: kota, dtype: object

In [9]:
loker['kota'].drop_duplicates(inplace=True)

In [10]:
loker = loker.dropna().reset_index()

Hitungannya berbeda karena data yang ada di Kota itu bukan berdasarkan karakter melainkan berdasarkan teks, pelajran yang saya dapat adalah ketelitian saat memeriksa data karena data tidak selalu rapi, bersih, dan terstruktur. Saya membutuhkan waktu hampir 30 menit untuk menyadari kalau 1 masalah nya itu ada di Case-Sensitive

Untuk gaji lowongan kerja yang tidak di isi akan tetap di hapus karena jika tidak data akan berantakan

In [51]:
loker['gaji_tengah'] = (loker['gaji_min_juta'] + loker['gaji_maks_juta']) / 2
loker['gaji_tengah']

0      4.00
1      4.75
2      7.00
3      8.50
4      3.40
5      6.00
6      4.25
7      4.00
8     15.00
9      4.50
10     4.50
11    10.00
12     5.25
13     6.50
14    11.00
15     8.00
16     5.25
17     4.00
Name: gaji_tengah, dtype: float64

In [52]:
for k in loker['kota'].unique():
    print(f'Kota: {k}, jumlah lowongan: {len(loker)}')

Kota: Malang, jumlah lowongan: 18
Kota: Surabaya, jumlah lowongan: 18
Kota: Jakarta, jumlah lowongan: 18
Kota: Batu, jumlah lowongan: 18

In [53]:
loker

,index,posisi,perusahaan,kota,pendidikan_min,pengalaman_min,gaji_min_juta,gaji_maks_juta,skill,tipe_kerja,gaji_tengah
0,0,Junior Web Developer,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO,4.00
1,1,Frontend Developer,CV Rumah Digital,Malang,SMK,1,4.0,5.5,JavaScript;React;HTML;CSS,Hybrid,4.75
2,2,Backend Developer,PT Arunika Solusi,Surabaya,D3,2,6.0,8.0,Python;Django;SQL;Git,Hybrid,7.00
3,3,Data Analyst,PT Data Cerdas,Jakarta,S1,1,7.0,10.0,Python;SQL;Excel,WFO,8.50
4,4,IT Support,PT Sinar Logistik,Malang,SMK,0,3.0,3.8,Jaringan;Windows;Linux,WFO,3.40
5,5,Mobile Developer,PT Aplikasi Kita,Surabaya,SMK,1,5.0,7.0,Flutter;Dart;Git,Hybrid,6.00
6,6,Game Developer,Studio Batu Kreatif,Batu,SMK,0,3.5,5.0,Unity;C#;Git,WFO,4.25
7,7,QA Tester,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,Testing;SQL;Git,WFO,4.00
8,8,Data Engineer,PT Data Cerdas,Jakarta,S1,3,12.0,18.0,Python;SQL;Cloud,Remote,15.00
9,10,UI/UX Designer,CV Rumah Digital,Malang,SMK,1,4.0,5.0,Figma;HTML;CSS,Hybrid,4.50
10,11,Junior Programmer,PT Sinar Logistik,Surabaya,SMK,0,4.0,5.0,Python;SQL,WFO,4.50
11,12,Web Developer,PT Nusa Web,Jakarta,S1,2,8.0,12.0,JavaScript;React;Node.js;Git,Remote,10.00
12,13,IT Support,PT Bank Daerah,Surabaya,D3,1,4.5,6.0,Jaringan;Windows,WFO,5.25
13,14,Data Analyst,PT Arunika Solusi,Surabaya,S1,0,5.5,7.5,Python;SQL;Excel;Power BI,Hybrid,6.50
14,15,Mobile Developer,PT Nusa Web,Jakarta,D3,2,9.0,13.0,Kotlin;Android;Git,Remote,11.00
15,17,Game Developer,PT Main Seru,Jakarta,D3,1,7.0,9.0,Unity;C#,Hybrid,8.00
16,18,Backend Developer,PT Kode Nusantara,Malang,SMK,1,4.5,6.0,PHP;Laravel;MySQL;Git,Hybrid,5.25
17,19,Junior Web Developer,PT Kode Nusantara,Malang,SMK,0,3.5,4.5,PHP;Laravel;MySQL;Git,WFO,4.00

In [54]:
smk = len(loker[loker['pendidikan_min'] == "SMK"])
all = len(loker)

In [55]:
presentase_smk = (smk / all)
print(f'Presentase smk = {presentase_smk * 100:.2f}%')

Presentase smk = 55.56%

In [56]:
loker.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           18 non-null     int64
 1   posisi          18 non-null     object
 2   perusahaan      18 non-null     object
 3   kota            18 non-null     object
 4   pendidikan_min  18 non-null     object
 5   pengalaman_min  18 non-null     int64
 6   gaji_min_juta   18 non-null     float64
 7   gaji_maks_juta  18 non-null     float64
 8   skill           18 non-null     object
 9   tipe_kerja      18 non-null     object
 10  gaji_tengah     18 non-null     float64
dtypes: float64(3), int64(2), object(6)
memory usage: 1.7+ KB

* Tahap 3

In [64]:
for kota, pengalaman,thn, gaji in zip(loker['kota'], loker['pendidikan_min'], loker['pengalaman_min'],loker['gaji_tengah']):
    print(kota, pengalaman,thn, gaji)

Malang SMK 0 4.0
Malang SMK 1 4.75
Surabaya D3 2 7.0
Jakarta S1 1 8.5
Malang SMK 0 3.4
Surabaya SMK 1 6.0
Batu SMK 0 4.25
Malang SMK 0 4.0
Jakarta S1 3 15.0
Malang SMK 1 4.5
Surabaya SMK 0 4.5
Jakarta S1 2 10.0
Surabaya D3 1 5.25
Surabaya S1 0 6.5
Jakarta D3 2 11.0
Jakarta D3 1 8.0
Malang SMK 1 5.25
Malang SMK 0 4.0

* Tahap 3

In [65]:
loker.columns

Index(['index', 'posisi', 'perusahaan', 'kota', 'pendidikan_min',
       'pengalaman_min', 'gaji_min_juta', 'gaji_maks_juta', 'skill',
       'tipe_kerja', 'gaji_tengah'],
      dtype='object')

In [66]:
kondisi = (loker['pendidikan_min'] == 'SMK') & (loker['pengalaman_min'] == 0)
df_smk = loker[kondisi]
hasil = df_smk[['posisi', 'perusahaan', 'kota', 'gaji_tengah']]

In [67]:
hasil

                  posisi           perusahaan      kota  gaji_tengah
0   Junior Web Developer    PT Kode Nusantara    Malang         4.00
4             IT Support    PT Sinar Logistik    Malang         3.40
6         Game Developer  Studio Batu Kreatif      Batu         4.25
7              QA Tester    PT Kode Nusantara    Malang         4.00
10     Junior Programmer    PT Sinar Logistik  Surabaya         4.50
17  Junior Web Developer    PT Kode Nusantara    Malang         4.00

In [68]:
git = loker[loker['skill'].str.contains('Git')]
git [['posisi', 'perusahaan', 'skill']]

                  posisi           perusahaan                         skill
0   Junior Web Developer    PT Kode Nusantara         PHP;Laravel;MySQL;Git
2      Backend Developer    PT Arunika Solusi         Python;Django;SQL;Git
5       Mobile Developer     PT Aplikasi Kita              Flutter;Dart;Git
6         Game Developer  Studio Batu Kreatif                  Unity;C#;Git
7              QA Tester    PT Kode Nusantara               Testing;SQL;Git
11         Web Developer          PT Nusa Web  JavaScript;React;Node.js;Git
14      Mobile Developer          PT Nusa Web            Kotlin;Android;Git
16     Backend Developer    PT Kode Nusantara         PHP;Laravel;MySQL;Git
17  Junior Web Developer    PT Kode Nusantara         PHP;Laravel;MySQL;Git

In [69]:
sql = loker[loker['skill'].str.contains('SQL')]
sql [['posisi', 'perusahaan', 'skill']]

                  posisi         perusahaan                      skill
0   Junior Web Developer  PT Kode Nusantara      PHP;Laravel;MySQL;Git
2      Backend Developer  PT Arunika Solusi      Python;Django;SQL;Git
3           Data Analyst     PT Data Cerdas           Python;SQL;Excel
7              QA Tester  PT Kode Nusantara            Testing;SQL;Git
8          Data Engineer     PT Data Cerdas           Python;SQL;Cloud
10     Junior Programmer  PT Sinar Logistik                 Python;SQL
13          Data Analyst  PT Arunika Solusi  Python;SQL;Excel;Power BI
16     Backend Developer  PT Kode Nusantara      PHP;Laravel;MySQL;Git
17  Junior Web Developer  PT Kode Nusantara      PHP;Laravel;MySQL;Git

Tidak ada lowongan lain selain lowongan yang meminta SQL

In [72]:
df_split = loker['skill'].str.split(';')
df_exploded = df_split.explode()
df_exploded = df_exploded.str.strip()
top5_skill = df_exploded.value_counts().head(5)
top5_skill

skill
Git        9
SQL        6
Python     5
Laravel    3
MySQL      3
Name: count, dtype: int64

In [80]:
lowongan_remot = loker[loker['tipe_kerja'].str.lower() == 'remote']['kota'].value_counts()
lowongan_remot

kota
Jakarta    3
Name: count, dtype: int64

In [82]:
loker.columns

Index(['index', 'posisi', 'perusahaan', 'kota', 'pendidikan_min',
       'pengalaman_min', 'gaji_min_juta', 'gaji_maks_juta', 'skill',
       'tipe_kerja', 'gaji_tengah'],
      dtype='object')

In [91]:
loker.groupby('tipe_kerja')[['kota', 'pendidikan_min', 'gaji_tengah']].apply(lambda loker: loker.loc[loker.idxmax()].value_counts())

tipe_kerja  kota      pendidikan_min  gaji_tengah
Hybrid      Jakarta   D3              8.00           1
            Malang    SMK             4.75           1
            Surabaya  D3              7.00           1
Remote      Jakarta   S1              15.00          3
WFO         Jakarta   S1              8.50           1
            Malang    SMK             4.00           1
            Surabaya  SMK             4.50           1
Name: count, dtype: int64

Ya, kerja remote di gaji lebih tinggi dari pada kerja WFO

* **Kota manakah yang memberikan rata-rata gaji tertinggi bagi lulusan SMK, dan perusahaan apa yang menawarkan gaji tertinggi untuk lulusan tersebut di kota tersebut?**

In [92]:
df_smk = loker[loker['pendidikan_min'].str.lower() == 'smk']
r_gaji_smk_kota = df_smk.groupby('kota')['gaji_tengah'].mean().reset_index()
r_gaji_smk_kota = r_gaji_smk_kota.sort_values(by='gaji_tengah', ascending=False)
print('-- Rata-rata Gaji lulusan SMK per Kota --')
print(r_gaji_smk_kota.to_string(index=False))

-- Rata-rata Gaji lulusan SMK per Kota --
    kota  gaji_tengah
Surabaya     5.250000
  Malang     4.271429
    Batu     4.250000

In [93]:
kota_tertinggi = r_gaji_smk_kota.iloc[0]['kota']
df_smk_k_top = df_smk[df_smk['kota'] == kota_tertinggi]
baris_s_smk = df_smk_k_top.loc[df_smk_k_top['gaji_tengah'].idxmax()]
print(f'-- Perusahaan dengan Gaji SMK Tertinggi di {kota_tertinggi} --')
print(f'Perusahaan : {baris_s_smk['perusahaan']}')
print(f'Posisi : {baris_s_smk['posisi']}')
print(f'Gaji Tengah : {baris_s_smk['gaji_tengah']} Juta')

-- Perusahaan dengan Gaji SMK Tertinggi di Surabaya --
Perusahaan : PT Aplikasi Kita
Posisi : Mobile Developer
Gaji Tengah : 6.0 Juta